image:
  repository: path/to/repo
  tag:
  pullPolicy: Always

service:
    name: ms-chat-service
    
resources:
limits:
    cpu: 300m
    memory: 460Mi
requests:
    cpu: 50m
    memory: 64Mi
    
springProfilesActive: cloud,ci,dov

livenessProbe:
    path: /api/actuator/health
readinessProbe:
    path: /api/actuator/health
    
server:
    xms: "64m"
    xmx: "450m"
    
selector:
  matchLabels:
    app: chat-service-backend
