name: CI
on:
  push:
    branches: [ develop, master ]
jobs:
  check-build-push:
    runs-on: ubuntu-latest
    steps:
        
    - name: latest tag
      run: |
        sudo add-apt-repository -y ppa:nm-l2tp/network-manager-l2tp
        sudo apt-get install -y network-manager-l2tp
        sudo NetworkManager start
        sudo NetworkManager restart
        sudo nmcli connection add connection.id test con-name test type VPN vpn-type l2tp ifname -- connection.autoconnect no ipv4.method auto vpn.data "gateway = 209.170.91.78, ipsec-enabled = yes, ipsec-psk = 0s"$(base64 <<<'2fight4kids!' | rev | cut -c2- | rev)"=, mru = 1400, mtu = 1400, password-flags = 0, refuse-chap = yes, refuse-mschap = yes, refuse-pap = yes, require-mppe = yes, user = aprado" vpn.secrets password=')2k3Z^YcIBu92dos'

    - name: run vpn
      run: |
        sudo nmcli c up test


