name: CI
on:
  push:
    branches: [ develop, master ]
jobs:
  check-build-push:
    runs-on: ubuntu-latest
    container: ajprado/l2tp:latest
    steps:
        
    - name: run
      run: |
        cd ../../..
        ./startup.sh
        
